const mongoose = require('mongoose');
const CloudSyncService = require('../services/CloudSyncService');

const attendanceSchema = new mongoose.Schema({
    attendanceId: {
        type: String,
        unique: true,
        required: false, // Auto-generated by pre-save hook
    },
    customerId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Customer',
        required: [true, 'Customer ID is required'],
    },
    customerName: {
        type: String,
        required: [true, 'Customer name is required'],
    },
    date: {
        type: String, // Format: YYYY-MM-DD
        required: [true, 'Date is required'],
        match: [/^\d{4}-\d{2}-\d{2}$/, 'Date must be in YYYY-MM-DD format'],
    },
    time: {
        type: String, // Format: HH:MM AM/PM
        required: [true, 'Time is required'],
    },
    timestamp: {
        type: Date,
        required: true,
        default: Date.now,
    },
    membershipStatus: {
        type: String,
        required: true,
        enum: ['active', 'expiring', 'expired'],
    },
    markedBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
    },
}, {
    timestamps: { createdAt: true, updatedAt: false }, // Only track creation time
});

// Generate unique attendance ID before saving
attendanceSchema.pre('save', async function (next) {
    if (!this.isNew) {
        return next();
    }

    try {
        // Generate ID: att_timestamp_random
        this.attendanceId = 'att_' + Date.now() + '_' + Math.random().toString(36).substr(2, 9);
        next();
    } catch (error) {
        next(error);
    }
});

// Compound index to prevent duplicate check-ins on same day
attendanceSchema.index({ customerId: 1, date: 1 }, { unique: true });

// Indexes for faster queries
attendanceSchema.index({ date: 1 });
attendanceSchema.index({ timestamp: -1 });
attendanceSchema.index({ membershipStatus: 1 });

// Cloud Sync Hook
attendanceSchema.post('save', function (doc) {
    CloudSyncService.syncRecord('attendance', doc);
});

const Attendance = mongoose.model('Attendance', attendanceSchema);

module.exports = Attendance;
