const mongoose = require('mongoose');
const CloudSyncService = require('../services/CloudSyncService');

const paymentSchema = new mongoose.Schema({
    paymentId: {
        type: String,
        unique: true,
        required: false, // Auto-generated by pre-save hook
    },
    customerId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Customer',
        required: [true, 'Customer ID is required'],
    },
    customerName: {
        type: String,
        required: [true, 'Customer name is required'],
    },
    amount: {
        type: Number,
        required: [true, 'Payment amount is required'],
        min: [0, 'Amount cannot be negative'],
    },
    paymentDate: {
        type: Date,
        required: [true, 'Payment date is required'],
        default: Date.now,
    },
    paymentMethod: {
        type: String,
        required: [true, 'Payment method is required'],
        enum: {
            values: ['Cash', 'Card', 'UPI', 'Bank Transfer', 'Cheque', 'Other'],
            message: '{VALUE} is not a valid payment method',
        },
    },
    receiptNumber: {
        type: String,
        trim: true,
        default: '',
    },
    planType: {
        type: String,
        required: [true, 'Plan type is required'],
        enum: ['Monthly', 'Quarterly', 'Half-Yearly', 'Yearly'],
    },
    status: {
        type: String,
        required: true,
        enum: ['completed', 'pending', 'failed'],
        default: 'completed',
    },
    notes: {
        type: String,
        trim: true,
        default: '',
    },
    addedBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
    },
}, {
    timestamps: true,
});

// Generate unique payment ID before saving
paymentSchema.pre('save', async function (next) {
    if (!this.isNew) {
        return next();
    }

    try {
        // Generate ID: pay_timestamp_random
        this.paymentId = 'pay_' + Date.now() + '_' + Math.random().toString(36).substr(2, 9);
        next();
    } catch (error) {
        next(error);
    }
});

// Indexes for faster queries
paymentSchema.index({ paymentId: 1 });
paymentSchema.index({ customerId: 1 });
paymentSchema.index({ paymentDate: -1 });
paymentSchema.index({ status: 1 });

// Cloud Sync Hook
paymentSchema.post('save', function (doc) {
    CloudSyncService.syncRecord('payment', doc);
});

const Payment = mongoose.model('Payment', paymentSchema);

module.exports = Payment;
